### ISSUE TITLE
how to install on macos?

### ISSUE THREAD

**Issue by Commod0re** [setvisible/ArrowDL#126]
I went to install ArrowDL on a mac but there appear to be no release files. I looked in the `.tar.gz` file but that looks like a linux build, and the install script didn't work anyway because it isn't compatible with bsd sed

so... is there actually a way to install on macos? are we supposed to build it ourselves? can you provide any guidance?

thanks in advance

**Comment by setvisible** [comment]
Hi,

The .tar.gz is Linux build. It's probably not working well with MacOs.

Maybe the most efficient is to add a new `macos` target to `.github/workflows/deployment.yml` in the `ubuntu` manner and see how it goes.

That's cool because I didn't know that Macos runners were now available:
https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/

For your question, I would suggest to adapt the `deployment.yml` to build the application... So, if you want to contribute.... On my side I cannot garantee to help soon because my time is currently spent to a house move. If you do it and if it works, put your changes on a Pull Request so that your contribution could be deployed. 

Regards,

**Comment by Commod0re** [comment]
maybe you should take the stuff off your website that says you have macos redistributables since you actually don't have any

Unfortunately building from source is not a good solution for me, thanks anyway
