### ISSUE TITLE
libcurl webassembly

### ISSUE THREAD

**Issue by trimechee** [setvisible/ArrowDL#148]
Hello, I have already talked about VCap Downloader (VCapDL), an innovative project that invents the concept of a web browser with integrated curl:

https://curl.se/

for a more efficient download of audio and video streams outside of the censorship of the stores :

https://vcapdl.com/

and I discover today this promising project "libcurl" which allows to integrate curl webassembly in web browsers, maybe this project can help ArrowDL to intercept more streams :

https://github.com/ading2210/libcurl.js
https://www.npmjs.com/package/libcurl.js

https://github.com/MercuryWorkshop/epoxy-tls

https://ading.dev/projects/

**Comment by setvisible** [comment]
Hi,

Thanks for the proposition.

My 2 cents: Curl is an standalone library, and is redondant with Qt6, because Qt6 already implements the network connection. There's no need for using Curl at this point I guess. Moreover a javascript library requires a web browser, and the purpose of ArrowDL is to download internet resources without the help of a web browser.

I'll close the proposition.

Cheers,
